safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: yandex2
default_width: 1920
default_ratio: 16x10     # 4x3, 16x9, 16x10
default_lang: en
default_body_class: list

presentation:
    title: Design and Implementation of DBMS Asynchronous Client Library
    service: Mail
    nda: false
    lang: en            # ru, en

author:
    email: elsid@yandex-team.ru
    name: Roman Siromakha
    company:
        name: Yandex
        url:  https://mail.yandex.ru/

fork_url: https://github.yandex-team.ru/presentation/jekyller
progress: true # отображение прогресс-бара в нижней части слайдов
